name: Scan new pypi pkgs
on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'


jobs:
  scan_new_pypi_pkgs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: install semgrep 
      run: pip3 install semgrep

    - name: clone rules repo
      run: |
        git clone https://github.com/h4sh5/h4sh-semgrep-rules

    - name: get new packages names
      run: python3 get_packages.py | tee new.txt


    - name: download all new packages
      run: |
        mkdir packages;
        cd packages;
        cat ../new.txt | parallel pip download || echo ignoring some error $?
        for i in *; do unzip -- "$i"; done || echo ignorin error $?

    - name: run semgrep scan
      run: |
        semgrep --json -c h4sh-semgrep-rules/python packages/ | tee report.json

    - name: high risk pkgs detection
      run: |
        python3 raise_high_risk_pkgs.py

    - name: Push scanned packages to cache
      run: | 
        cat new.txt | sort -u >> scanned_pkgs.txt
        git add *.txt *.csv
        git config --global user.name 'PyPi Scan Bot by h4sh'
        git config --global user.email 'pypi-scan-bot-h4sh@open-source.local'
        git commit -m "new scan output $(date)"
        git push 

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: new-scan-report
        path: report.json




